version: "3.9"

services:
  database:
    container_name: database-server-dab-p1-b7c7d0d1-d2ff-4ef4-9553-e95ea3225629
    image: postgres:15
    restart: 'no'
    env_file: 
      - .env.development
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 64M

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: 'no'
    expose:
      - 6379

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file: .env.development
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    restart: 'no'
    volumes:
      - ./backend/:/app
      - ./app-cache/:/app-cache
    expose:
      - 8000
    depends_on:
      - database
      - redis
      - flyway
    env_file:
      - .env.development
    deploy:
      replicas: 2

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    volumes:
      - ./frontend/:/app
      - vite_node_modules:/app/node_modules
    restart: 'no'
    expose:
      - 5173
    depends_on:
      - backend
    env_file:
      - .env.development
  
  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    image: llm
    restart: 'no'
    expose:
      - 7000
    volumes:
      - ./llm/:/app
      - ./app-cache/:/app-cache
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 64M

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
      - llm
    ports:
      - 7800:7800

volumes:
  vite_node_modules:

